name: Deploy to Production Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install SSH and rsync
        run: sudo apt-get update && sudo apt-get install -y sshpass openssh-client rsync

      - name: Copy project to remote server via rsync
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" rsync -avz --delete --exclude=".env" \
            -e "ssh -o StrictHostKeyChecking=no -p 22100" \
            ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.SSH_APP_PATH }}/

      - name: Build and run using Docker Compose on remote server
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no -p 22100 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd ${{ secrets.SSH_APP_PATH }}
            echo "Derrubando containers antigos..."
            docker compose down || true
            echo "Subindo containers com Docker Compose..."
            docker compose up -d --build --force-recreate --remove-orphans lawsuit-metadata-api
          EOF
